### ISSUE TITLE
I have some questions about the dataset CUB

### ISSUE THREAD

**Issue by Wangjunyue** [edgarschnfld/CADA-VAE-PyTorch#1]

**Comment by Wangjunyue** [comment]
In the paper CADA-VAE, the sentences are used in the CUB dataset. I download the dataset "cvpr2016_cub", however I have no idea about how to process the features. Could you share how to use the features?

**Comment by edgarschnfld** [comment]
If you want to use the sentence features, you do not have to download any additional data, apart from the dropbox link that is provided by the readme. To train the model using sentence features, go to single_experiment.py and change line 49 from
**'auxiliary_data_source': 'attributes'**
to
**'auxiliary_data_source': 'sentences'.**
We use the same pre-computed sentence features as in "feature generating networks for zero-shot learning" [1], without any extra processing steps.

[1] Xian, Yongqin, et al. "Feature generating networks for zero-shot learning." Proceedings of the IEEE conference on computer vision and pattern recognition. 2018.

**Comment by Wangjunyue** [comment]
Thank you for your reply, which is very helpful to me. And I will quickly verify whether the features are useful to me.

At 2019-05-06 17:52:06, "edgarschnfld" <notifications@github.com> wrote:


If you want to use the sentence features, you do not have to download any additional data, apart from the dropbox link that is provided by the readme. To train the model using sentence features, go to single_experiment.py and change line 49 from
'auxiliary_data_source': 'attributes'
to
'auxiliary_data_source': 'sentences'.
We use the same pre-computed sentence features as in "feature generating networks for zero-shot learning" [1], without any extra processing steps.

[1] Xian, Yongqin, et al. "Feature generating networks for zero-shot learning." Proceedings of the IEEE conference on computer vision and pattern recognition. 2018.
