### ISSUE TITLE
Can this model test on dataset like ImageNet?

### ISSUE THREAD

**Issue by flash1803** [edgarschnfld/CADA-VAE-PyTorch#11]
Hi,  I like your work, it's brilliant and has so much potential. I've noticed that your model didn't test on large scale dataset like ImageNet. Well, more and more zsl models are focusing on this in order to get closer to the real world scenario. So I'm wondering if it's ok to test on ImageNet dataset? (ImageNet 1K as training set . 2-hops/3-hops/All as testing set)

**Comment by edgarschnfld** [comment]
Hey, thank you for the kind words. Actually, we did test the model on ImageNet. The numbers are in the paper :) 
Best,
Edgar
