### ISSUE TITLE
Could you please provide a link for imagenet features ?

### ISSUE THREAD

**Issue by lixiaorui4444** [edgarschnfld/CADA-VAE-PyTorch#13]
Hi, Could you please provide a link for imagenet features ? I build a mixed Guassian distribution, and I want to test it performance, thank you very much!

**Comment by edgarschnfld** [comment]
Hi, the imagenet features are provided by the dropbox link below, which contains two mat files. Let me know if you encounter any problems with the data or something is unclear.

https://www.dropbox.com/sh/k63wtetx6jq6y7s/AACONMxqlQa5s16qqs7Gkctfa?dl=0

**Comment by lixiaorui4444** [comment]
Thank you very much!!

**Comment by edgarschnfld** [comment]
And the word2vec data is found here https://github.com/pujols/zero-shot-learning

**Comment by edgarschnfld** [comment]
And the training- as well as test-data is also found here https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/zero-shot-learning/zero-shot-learning-the-good-the-bad-and-the-ugly/

**Comment by a494456818** [comment]
> Hi, the imagenet features are provided by the dropbox link below, which contains two mat files. Let me know if you encounter any problems with the data or something is unclear.
> 
> https://www.dropbox.com/sh/k63wtetx6jq6y7s/AACONMxqlQa5s16qqs7Gkctfa?dl=0

Could you please share the imagenet features again? I found that this link doesn't work. Thank you very much !
