### ISSUE TITLE
questions about the hyperparameters

### ISSUE THREAD

**Issue by zhaizhibo** [edgarschnfld/CADA-VAE-PyTorch#23]
Hi, I don't understand what the cls_train_steps and num_shots parameters mean. Could you please explain them for me simply?

**Comment by edgarschnfld** [comment]
Hi, 
Training proceeds in two phases: First we train the VAE to learn the shared embedding, then we train the classifier separately on embedded features. ```cls_train_steps``` is the number of training steps of that classifier.  Classifier training relies on early stopping, so the ```cls_trainsteps``` were determined on the hyperparameter tuning split to know when to end training. ```num_shots``` is the number of shots: if it is 0 we do 0-shot learning, if it is 1 we do 1-shot learning, and so on.

**Comment by KernLC** [comment]
Thanks a lot!!

**Comment by zhaizhibo** [comment]
> Hi,
> Training proceeds in two phases: First we train the VAE to learn the shared embedding, then we train the classifier separately on embedded features. `cls_train_steps` is the number of training steps of that classifier. Classifier training relies on early stopping, so the `cls_trainsteps` were determined on the hyperparameter tuning split to know when to end training. `num_shots` is the number of shots: if it is 0 we do 0-shot learning, if it is 1 we do 1-shot learning, and so on.

Thanks a lot!!!!
