### ISSUE TITLE
Attribute vector creation procedure

### ISSUE THREAD

**Issue by prashastbindal** [edgarschnfld/CADA-VAE-PyTorch#24]
Hi,

I am using your attributes file, but I am curious about how the attributes vectors are created because I need to create them for another dataset. I see there are two keys in the .mat file "original_att" and "att" with different statistics for the arrays. Is there some normalization that is performed on binary attribute vectors? If you have the .mat file creation script can you please share it

Thanks in advance !

**Comment by edgarschnfld** [comment]
Hi,

That question has been answered already earlier here in issue https://github.com/edgarschnfld/CADA-VAE-PyTorch/issues/14. Sorry for the late answer.
