### ISSUE TITLE
Problems encountered when loading data

### ISSUE THREAD

**Issue by Luodapang** [edgarschnfld/CADA-VAE-PyTorch#26]
Hi,  thank you for your work. It's so great!!!
I'm getting the error "TypeError: object of type 'DATA_LOADER' has no len()" when running the code. The error is located at "data.DataLoader(self.dataset, batch_size=self.batch_size, shuffle=True, drop_last=True)", Can you tell me how I can solve this problem?

**Comment by edgarschnfld** [comment]
Hi, does this #17 solve your problem?

**Comment by Luodapang** [comment]
Thank you! I have run the code successfully. Thanks for your reply!
