### ISSUE TITLE
Problems with SUN dataset

### ISSUE THREAD

**Issue by rfelixmg** [edgarschnfld/CADA-VAE-PyTorch#5]
Dear authors,

First, thank you so much for releasing the code you used for training. This shows the integrity and quality of your research. For most of the benchmarks, I've managed to get very similar results that you report in the paper. However, I am finding very hard to get the same reported values for SUN The best that I manage to achieve was:
S       U        H
37 | 40.5 | 38.7

Whereas you report
S       U        H
35.7 | 47.2 | 40.6

I am using the hyper-parameters suggested in this repo. By any chance, have you used different hyper parameter to train the classifier?

Regards, Rafa.

**Comment by edgarschnfld** [comment]
Dear Rafa,

Thank you for reporting this. I am travelling at the moment but I will check this out as soon as possible and get back to you. Nevertheless, we used the same hyperparameters for all datasets.

Best,
Edgar
